### PR TITLE
Updated RuneLite version and fixed party imports

### PR DESCRIPTION
**Pull request by Chronoes**

### CODE REVIEW

**Comment by robmonte** [comment]
@Chronoes Is this all that's needed to get the plugin working again with the recent party update? Do you know if there's any other broken functionality?

**Comment by Chronoes** [comment]
@robmonte It doesn't seem like there's any functionality that was changed during refactoring in [this commit](https://github.com/runelite/runelite/commit/82c93f45da679ad08b2828e157cbb7c2fb539c5c#diff-8cbd3b6a6b9d11c0b98af852e3a26367775baeab45196c8927e3be5e25eb2152).

I also tested with 2 accounts in a party and it seems to be working fine. I only got a little bit of experience using this plugin in the previous version before it disappeared with RuneLite update.

**Comment by robmonte** [comment]
@Chronoes Looks like this fixes it up to work for me as well. The version is now 1.8.23 if you want to bump it again while waiting for TheStonedTurtle to merge.

The plugin will need a couple changes again to account for Adam's party changes, like removing the Discord username as it now only states "rluser-#######" for everyone. And the plugin should be renamed from Discord Party Panel to something else, but for now just getting the plugin working again is ideal.

**Comment by Chronoes** [comment]
I can investigate the name issue further if you don't plan to yet. I wasn't initially sure what the rluser-#### name was exactly for but it seems like this was introduced a bit later. At least now I can more easily test against real users so thank you for your response.

**Comment by robmonte** [comment]
@Chronoes Thanks for getting the plugin fixed. TheStonedTurtle also took care of the rluser line and the name of the plugin after merging your PR.

**Pull request merged**
